webservers:
  hosts:
    web1:
    ansible_host:
      web1.server.com
    ansible_connection:
      ssh
    web2.server.com

dbservers:
  hosts:
    web1.server.com

loadbalancer:
  hosts:
    lb1.server.com

frontendservers:
  children:
    loadbalancer:
    webservers: