- name: Install required packages
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      shell:
        a2enmod ssl
        a2enmod proxy
        a2enmod proxy_balancer
        a2enmod proxy_http
        a2enmod lbmethod_byrequests
      args:
        executable: /bin/bash
      ignore_errors: yes





