- name: Stop and Uninstall APache server
  hosts: local
  become: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: Stop Apache
      service:
        name: "{{ package_name  }}"
        state: stopped
        enabled: false
    - name: Delete Apache
      apt:
        name: "{{ package_name }}"
        state: absent